---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'add a domain to a Serverless app'

Parameters:
  ApiGatewayRestApiId:
    Description: 'where we can put temporary files in the bucket'
    Type: String
  ApiGatewayStage:
    Description: 'where we can put temporary files in the bucket'
    Type: String
  Hostname:
    Description: 'the full hostname we want to be available on the Internet'
    Type: String
  HostedZoneName:
    Description: 'the "name" of the Route53 hosted zone (i.e. the domain plus a period)'
    Type: String
  RegionalCertificateArn:
    Description: 'ARN of the ACM certificiate for this host'
    Type: String


Resources:

  ApiGatewayDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref Hostname
      EndpointConfiguration:
        Types:
          - 'REGIONAL'
      RegionalCertificateArn: !Ref RegionalCertificateArn

  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: ApiGatewayDomainName
    Properties:
      BasePath: ''
      DomainName: !Ref Hostname
      RestApiId: !Ref ApiGatewayRestApiId
      Stage: !Ref ApiGatewayStage

  RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
        - Name: !Ref Hostname
          Type: A
          AliasTarget:
            DNSName: !GetAtt ApiGatewayDomainName.RegionalDomainName
            HostedZoneId: !GetAtt ApiGatewayDomainName.RegionalHostedZoneId

