---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'create a Route 53 hosted zone'

Parameters:
  DomainName:
    Description: 'the base domain we want to attach hostnames to'
    Type: String


Resources:

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName


Outputs:
  NameServers:
    Value:
      !Join
        - ' '
        - !GetAtt HostedZone.NameServers