AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  WallGenerator:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: 's3://rgitzel-lambda-artifacts-us-west-2/azul-generator.zip'
    Events:
      Generate:
        Type: Api
        Properties:
          Path: /generate
          Method: post

