#!/usr/bin/env bash

set -eu

#
# destroy all stacks in the project in the right order (i.e. in
#  reverse of the order they were created)
#
# Generated by v2.5.0-lambda at Fri Mar 23 19:54:54 UTC 2018
#

PROFILE=${1:?profile is required}
REGION=${2:?region is required}
ENVIRONMENT=${3:?environment is required}


# long-lived stacks

FOLDERS=( \
    http-lambda \
)

for f in ${FOLDERS[@]} ; do
  (cd $f ; make clean AWS_PROFILE=${PROFILE} AWS_REGION=${REGION} STACK_ENV=${ENVIRONMENT})
done

